
name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Generate fresh package-lock.json (public registry)
        run: |
          rm -f .npmrc || true
          npm config set registry "https://registry.npmjs.org/"
         
          echo "Registry: $(npm config get registry)"
          rm -f package-lock.json
          npm install --package-lock-only
          if grep -nE "stratmac|nero\.service\.group" package-lock.json; then
            echo "ERROR: package-lock.json still points to the internal registry."
            exit 1
          fi
      - run: npm ci
      - run: npm run build
      # Optional but recommended for SPAs (lets BrowserRouter work on refresh):
      - run: cp dist/index.html dist/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
